name: Python Backend CI

on: [push, pull_request]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/flask-api
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Bandit security scan
        run: |
          pip install bandit
          bandit -r .