name: Node.js Backend CI

on: [push, pull_request]

jobs:
  node-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/node-api
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install